### PR TITLE
Fixed pruning bug. Pruning now works correctly for all minimum segmen…

### PR DESCRIPTION
**Pull request by Fisch-Alex**
…t lengths.

### CODE REVIEW

**Comment by AndrewC1998** [comment]
Hi Alex, there seems to be a couple of small syntax errors in your changes that are causing TRAVIS CI to throw the error. If you wish, I can send you the corrected file in an email or I can be more specific here.

**Comment by Fisch-Alex** [comment]
Hi Andrew, Sure feel free to email me or meet up (provided you are based at Lancaster)! Are you certain that the tests are failing because of syntax errors? It appears to run fine on my machine... When I run the tests on my machine, it fails some tests because the output is now slightly different from what it was before. However, I believe that this is down to a bug in the old version which this pull request aims to correct.

**Comment by rkillick** [comment]
I believe, from Andrew, that the problem as an index starting at 1 instead of 0 which is causing NA's in a matrix.

**Comment by Fisch-Alex** [comment]
Oh! In that case, Andrew, can I take you up on your email offer? I am struggling to isolate the error as it passes all tests on my machine and producing plots which look like the ones that are in package...

**Comment by rkillick** [comment]
This has been merged in commit "Pruning bug and TRAVIS CI fix #33"

Thanks for spotting this and proposing the bug fix.

**Comment by rkillick** [comment]
@Fisch-Alex  Just looking at this again.  If a point is delayed to be pruned (outside the "keep" window but close to tstar) but then goes into the "keep" window at a future tstar within the delay period, then the delayed pruning is not removed, i.e. it isn't reset to n+2.  So this then should be kept but I think it gets removed when the delay operation is enacted.  Should this happen?

**Pull request closed without merging**
